name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Get the tag
      id: get_tag
      run: |
        echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
        echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}
    - name: Install TeXLive
      env:
        # TODO: actually cache the installation
        TEXLIVE_INSTALL_PREFIX: ${{ runner.tool_cache }}/texlive
      run: |
        cd ${{ runner.temp }}
        wget -q http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
        tar -xzf install-tl-unx.tar.gz
        cd install-tl-20*
        cat << EOF > texlive.profile
        selected_scheme scheme-basic
        tlpdbopt_install_docfiles 0
        tlpdbopt_install_srcfiles 0
        tlpdbopt_autobackup 0
        tlpdbopt_sys_bin /usr/local/bin
        EOF
        ./install-tl --portable --profile=texlive.profile
        # NOTE: we need to regain ownership before creating symlinks
        sudo chown -R `whoami`:admin /usr/local/bin
        $TEXLIVE_INSTALL_PREFIX/bin/x86_64-linux/tlmgr path add
        tlmgr install alphalph booktabs hologo enumitem csquotes fancyvrb underscore zref multirow
    - name: Run build
      run: make VERSION=${{ steps.get_tag.outputs.tag }} dist/topiclongtable-${{ steps.get_tag.outputs.tag }}.zip
    - name: Submit to CTAN
      uses: paolobrasolin/ctan-submit-action@v1
      with:
        action: submit
        file_path: dist/topiclongtable-${{ steps.get_tag.outputs.tag }}.zip
        fields: |
          update: "true"
          pkg: topiclongtable
          version: ${{ steps.get_tag.outputs.version }}
          uploader: Paolo Brasolin
          email: paolo.brasolin@gmail.com 
    - name: Release on Github
      uses: docker://antonyurchenko/git-release:v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DRAFT_RELEASE: "false"
        CHANGELOG_FILE: "CHANGELOG.md"
        ALLOW_EMPTY_CHANGELOG: "false"
        ALLOW_TAG_PREFIX: "true"
        RELEASE_NAME: "topiclongtable ${{ steps.get_tag.outputs.tag }}"
      with:
        args: |
            dist/topiclongtable-${{ steps.get_tag.outputs.tag }}.zip
